apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: leet
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 3000
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/leet-challenge:e262c1c67d348c2f649a6a54e4a5ffd178ec446a298944ed701f0cf55494c569
