apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: zookeeper
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/zookeeper-challenge:93dd8c95eada830d9f3d3f0c0441fba58dcb0186eafcde423902a579df37e236
