apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: otp
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/otp-challenge:f064aac1740e36089b1bc1cfa0a7ebfbb366c6f8a417ad60025600e1039704a2
