apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: the-house-always-wins
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/the-house-always-wins-challenge:61aefd853ae0d527c97d9cd58d92bf42e25fed455cccb03e03e1c84893c3f458
