apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: golf
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/golf-challenge:849ab05e96d3754caa023749725361eada80bdaadfa00a68c155f00754e2c4e0
