apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: sstigolf
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: eu.gcr.io/imaginaryctf-2022/sstigolf-healthcheck:047fb996df51b15a6e8983baed5eb6dfd00423bf490258fc99b0e41f259e35e1
  image: eu.gcr.io/imaginaryctf-2022/sstigolf-challenge:1d20d4df7a48d800f8914657002ce64841ecff896399a857660b1e7cb805bc35
