apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: roocookie
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/roocookie-challenge:fdb282414f5dbee78556f9a2af4a0e1f240483a14e27c6aeb12f8ee5c4ff37cd
