apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: cybercook
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 8080
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/cybercook-challenge:f46b517499c702818b39102954b09f311a2b63b18486a7f7d554a02639763713
