apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: minecraft
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/minecraft-challenge:75654287ea0e16fee922c916d68635977edb875941477a05832e8ceb2ef1cd0d
