apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: pycrib
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/pycrib-challenge:d9d188a2adcc08dc8a0fc54377ca69b17cc96c52482abd01c2f23da2ec88a69b
