version: "3"
services:
  bot:
    build: .
    ports:
      - 8080:80
    privileged: true
    restart: always
    environment:
      TOKEN: ictf{c0ngrats_on_pWning_my_w4sm_hopefully_there_werent_any_cheese_solutions_b2810d1e}
