version: '3.3'
services:
  flagbot:
    build: .
    network_mode: bridge
    restart: always
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
