apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: pokemon-emerald
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/imaginaryctf-2022/pokemon-emerald-challenge:a7b88840ab4e440554845868fbb2cb2474ca64d363ce546dd4f26ee034d19e48
